  language: python
  python:
    - "2.7"
    - "3.5"
    - "3.6"

  sudo: required

  install:
    - cd python
    - python setup.py install
    - cd ..

  script:
    - cd python
    - pip install -U .[test,doc]
    - python -m nose2 -v
    - cd doc
    - pip install -r source/requirements.txt
    - make html
    - cd ../..

  after_success:
    - cd python
    - coveralls
    - cd ..
