  language: python
  python:
    - "3.5"
    - "3.6"
    - "3.7-dev"

  sudo: required

  dist: xenial

  addons:
    apt:
      packages:
        - libhdf5-dev
        - ffmpeg
        - pandoc

  cache: 
    - pip
    - apt

  install:
    - python setup.py install

  script:
    - pip install -U .[test]
    - python setup.py test
    - pip install -U .[doc]
    - cd doc; make html
    - cd ..

  after_success:
    - coveralls

  deploy:
    provider: pypi
    user: scottgigante
    password: ${PYPI_PASSWORD}
    distributions: sdist bdist_wheel
    skip_existing: true
    skip_cleanup: true
    on:
      tags: true
      branch: master
