  language: python
  python:
    - "3.5"
    - "3.6"
    - "3.7-dev"

  sudo: required

  addons:
    apt:
      packages:
        - libhdf5-dev

  cache: 
    - pip
    - apt

  install:
    - cd python; python setup.py install; cd ..

  script:
    - cd python; pip install -U .[test,doc]
    - python setup.py test
    - cd doc; make html; cd ../..

  after_success:
    - cd python; coveralls; cd ..
