  language: python
  python:
    - "3.5"
    - "3.6"
    - "3.7-dev"

  sudo: required

  dist: xenial

  addons:
    apt:
      packages:
        - libhdf5-dev
        - ffmpeg

  cache: 
    - pip
    - apt

  install:
    - cd python; python setup.py install; cd ..

  script:
    - cd python; pip install -U .[test,doc]
    - python setup.py test
    - cd doc; make html; cd ../..

  deploy:
    provider: pypi
    user: scottgigante
    password: ${PYPI_PASSWORD}
    distributions: sdist bdist_wheel
    skip_existing: true
    skip_cleanup: true
    on:
      tags: true
      branch: master

  after_success:
    - cd python; coveralls; cd ..
